type TrialBalance @collection(name: "trial_balances") {
    player: Player!
    amount: Float!
    date_time: Time!
}

type Bet @collection(name: "bets") {
    round: Round!
    player: Player!
    time_bet: Time!
    stake: Float!
    winnings: Float!
}

type Player @collection(name: "players") {
    discord_id: String! @index
    player_name: String!
    money: Float!
    bets: [Bet]! @relation
    trial_balances: [TrialBalance]! @relation
}

type Round @collection(name: "rounds") {
    member: String!
    start_time: Time!
    proposed_time: Time!
    command_channel: String!
    bets: [Bet]! @relation
    arrival_time: Time
}